### PR TITLE
Add support for Android P on Samsung

### PR DESCRIPTION
**Pull request by widget-**
Adds a new signature for Pie on Samsung devices.

Tested on Note 8 N950F build N950FXXU5ZSB1.

### CODE REVIEW

**Comment by widget-** [comment]
EdXposed working:

screenshot_20190217-225305_edxposed_installer

So far only tested with Exi for Swiftkey module.

**Comment by amakuramio** [comment]
This is huge, I will upgrade to pie later in the day, thanks

**Comment by amakuramio** [comment]
didnt work for s9+ unfortunately

**Comment by RikkaW** [comment]
@amakuramio Have you tried the diagnostic app in v13 release, what it says?

**Comment by jaiyya** [comment]
anyone have it working on galaxy s9+ ?

**Pull request merged**
